### PR TITLE
Join/Leave Orgs

### PR DESCRIPTION
**Pull request by seanmpage**
We can now join and leave an organization. No styling done on the link but it works  :)

### CODE REVIEW

**Comment by jasimper** [comment]
I not merge.

**Comment by seanmpage** [comment]
you merge now

**Comment by jasimper** [comment]
nope

**Comment by seanmpage** [comment]
palease

**Comment by easmith2** [comment]
SNEAK ATTACK

**Comment by jasimper** [comment]
fun ruiner :(

**Comment by easmith2** [comment]
... like a fox!

**Comment by jasimper** [comment]
You should've made him wait.

**Comment by seanmpage** [comment]
:)

**Pull request merged**
